import {$t} from "locale/index";
import { isEmpty, startCase } from "lodash";
import { isDynamicValue } from "utils/DynamicBindingUtils";
import type { FieldThemeStylesheet, SchemaItem } from "./constants";
import {
  ARRAY_ITEM_KEY,
  DataType,
  FieldType,
  ROOT_SCHEMA_KEY,
} from "./constants";
import { klonaRegularWithTelemetry } from "utils/helpers";

export const schemaItemStyles = {
  accentColor:
    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
  borderRadius:
    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
  boxShadow: "none",
};

// TODO: Fix this the next time the file is edited
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const schemaItemFactory = (item: any): SchemaItem => {
  return {
    isDisabled: false,
    isRequired: false,
    labelTextSize: "0.875rem",
    label: startCase(item.identifier),
    isVisible: true,
    children: {},
    dataType: DataType.STRING,
    defaultValue: `{{((sourceData, formData, fieldState) => (sourceData.${item.identifier}))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}`,
    fieldType: FieldType.TEXT_INPUT,
    sourceData: $t('schemaTestData.546316e01bed24e3'),
    isCustomField: false,
    accessor: item.identifier || "",
    identifier: item.identifier || "",
    originalIdentifier: item.identifier || "",
    position: 0,
    ...item,
  };
};

export const replaceBindingWithValue = (schemaItem: SchemaItem) => {
  if (isEmpty(schemaItem)) return {} as SchemaItem;

  const updatedSchemaItem = klonaRegularWithTelemetry(
    schemaItem,
    "schemaTestData.replaceBindingWithValue",
  );

  Object.keys(updatedSchemaItem).forEach((k) => {
    const key = k as keyof SchemaItem;

    if (key === "children") {
      const schema = schemaItem[key];

      Object.keys(schema).forEach((itemKey) => {
        updatedSchemaItem.children[itemKey] = replaceBindingWithValue(
          schemaItem.children[itemKey],
        );
      });
    }

    if (isDynamicValue(schemaItem[key])) {
      updatedSchemaItem[key] = "test" as never;
    }
  });

  return updatedSchemaItem;
};

const initialDataset = {
  dataSource: {
    name: $t('schemaTestData.546316e01bed24e3'),
    age: 20,
    dob: "10/12/2021",
    boolean: true,
    hobbies: ["travelling", "skating", "off-roading"],
    "%%": "%",
    हिन्दि: "हिन्दि",
    education: [
      {
        college: $t('schemaTestData.cbeb6f28d88feaa9'),
        number: 1,
        graduationDate: "10/12/2021",
        boolean: true,
      },
    ],
    address: {
      Line1: $t('schemaTestData.cbeb6f28d88feaa9'),
      city: "1",
    },
  },

  schemaOutput: {
    __root_schema__: {
      isDisabled: false,
      isRequired: false,
      labelTextSize: "0.875rem",
      label: "",
      isVisible: true,
      children: {
        name: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.e6842984605930e9'),
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.name))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.TEXT_INPUT,
          iconAlign: "left",
          sourceData: $t('schemaTestData.546316e01bed24e3'),
          isCustomField: false,
          accessor: "name",
          identifier: "name",
          originalIdentifier: "name",
          position: 0,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        age: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.d17cce405d14d3db'),
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.NUMBER,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.age))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.NUMBER_INPUT,
          iconAlign: "left",
          sourceData: 20,
          isCustomField: false,
          accessor: "age",
          identifier: "age",
          originalIdentifier: "age",
          position: 1,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        dob: {
          closeOnSelection: false,
          dateFormat: "MM/DD/YYYY",
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.0aaed11e816c0059'),
          maxDate: "2121-12-31T18:29:00.000Z",
          minDate: "1920-12-31T18:30:00.000Z",
          shortcuts: false,
          isVisible: true,
          convertToISO: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            '{{((sourceData, formData, fieldState) => (moment(sourceData.dob, "MM/DD/YYYY").format("YYYY-MM-DDTHH:mm:ss.sssZ")))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}',
          fieldType: FieldType.DATEPICKER,
          timePrecision: "minute",
          sourceData: "10/12/2021",
          isCustomField: false,
          accessor: "dob",
          identifier: "dob",
          originalIdentifier: "dob",
          position: 2,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        boolean: {
          alignWidget: "LEFT",
          isDisabled: false,
          isRequired: false,
          isVisible: true,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.ae6da85839ef34ba'),
          children: {},
          dataType: DataType.BOOLEAN,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.boolean))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.SWITCH,
          sourceData: true,
          isCustomField: false,
          accessor: "boolean",
          identifier: "boolean",
          originalIdentifier: "boolean",
          position: 3,
          backgroundColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        hobbies: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.c6daaeb60a5a6839'),
          isVisible: true,
          serverSideFiltering: false,
          options: [
            { label: $t('schemaTestData.99051cd50140c8ee'), value: "BLUE" },
            { label: $t('schemaTestData.6e385a18e993129a'), value: "GREEN" },
            { label: $t('schemaTestData.98870409aa4c6131'), value: "RED" },
          ],
          children: {},
          dataType: DataType.ARRAY,
          defaultValue: `{{((sourceData, formData, fieldState) => (sourceData.hobbies))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}`,
          fieldType: FieldType.MULTISELECT,
          isFilterable: false,
          sourceData: ["travelling", "skating", "off-roading"],
          isCustomField: false,
          accessor: "hobbies",
          identifier: "hobbies",
          originalIdentifier: "hobbies",
          position: 4,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        __: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: "%%",
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            '{{((sourceData, formData, fieldState) => (sourceData["%%"]))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}',
          fieldType: FieldType.TEXT_INPUT,
          iconAlign: "left",
          sourceData: "%",
          isCustomField: false,
          accessor: "%%",
          identifier: "__",
          originalIdentifier: "%%",
          position: 5,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        xn__j2bd4cyac6f: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: "हिन्दि",
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            '{{((sourceData, formData, fieldState) => (sourceData["हिन्दि"]))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}',
          fieldType: FieldType.TEXT_INPUT,
          iconAlign: "left",
          sourceData: "हिन्दि",
          isCustomField: false,
          accessor: "हिन्दि",
          identifier: "xn__j2bd4cyac6f",
          originalIdentifier: "हिन्दि",
          position: 6,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        education: {
          backgroundColor: "#FAFAFA",
          isCollapsible: true,
          isDisabled: false,
          isRequired: false,
          isVisible: true,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.10a1cd2565283d7c'),
          children: {
            __array_item__: {
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.80fb12de536f6fd8'),
              isVisible: true,
              children: {
                college: {
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.76b513503aa00c46'),
                  isVisible: true,
                  isSpellCheck: false,
                  children: {},
                  dataType: DataType.STRING,
                  defaultValue: undefined,
                  fieldType: FieldType.TEXT_INPUT,
                  iconAlign: "left",
                  sourceData: $t('schemaTestData.cbeb6f28d88feaa9'),
                  isCustomField: false,
                  accessor: "college",
                  identifier: "college",
                  originalIdentifier: "college",
                  position: 0,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                number: {
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.66abdebf9a08121c'),
                  isVisible: true,
                  isSpellCheck: false,
                  children: {},
                  dataType: DataType.NUMBER,
                  defaultValue: undefined,
                  fieldType: FieldType.NUMBER_INPUT,
                  iconAlign: "left",
                  sourceData: 1,
                  isCustomField: false,
                  accessor: "number",
                  identifier: "number",
                  originalIdentifier: "number",
                  position: 1,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                graduationDate: {
                  closeOnSelection: false,
                  dateFormat: "MM/DD/YYYY",
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.369a4178adbfbc0d'),
                  maxDate: "2121-12-31T18:29:00.000Z",
                  minDate: "1920-12-31T18:30:00.000Z",
                  shortcuts: false,
                  isVisible: true,
                  children: {},
                  dataType: DataType.STRING,
                  defaultValue: undefined,
                  fieldType: FieldType.DATEPICKER,
                  timePrecision: "minute",
                  convertToISO: false,
                  sourceData: "10/12/2021",
                  isCustomField: false,
                  accessor: "graduationDate",
                  identifier: "graduationDate",
                  originalIdentifier: "graduationDate",
                  position: 2,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                boolean: {
                  alignWidget: "LEFT",
                  isDisabled: false,
                  isRequired: false,
                  isVisible: true,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.ae6da85839ef34ba'),
                  children: {},
                  dataType: DataType.BOOLEAN,
                  defaultValue: undefined,
                  fieldType: FieldType.SWITCH,
                  sourceData: true,
                  isCustomField: false,
                  accessor: "boolean",
                  identifier: "boolean",
                  originalIdentifier: "boolean",
                  position: 3,
                  backgroundColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
              },
              dataType: DataType.OBJECT,
              defaultValue: undefined,
              fieldType: FieldType.OBJECT,
              sourceData: {
                college: $t('schemaTestData.cbeb6f28d88feaa9'),
                number: 1,
                graduationDate: "10/12/2021",
                boolean: true,
              },
              isCustomField: false,
              accessor: ARRAY_ITEM_KEY,
              identifier: ARRAY_ITEM_KEY,
              originalIdentifier: ARRAY_ITEM_KEY,
              position: -1,
            },
          },
          dataType: DataType.ARRAY,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.education))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.ARRAY,
          sourceData: [
            {
              boolean: true,
              college: $t('schemaTestData.cbeb6f28d88feaa9'),
              graduationDate: "10/12/2021",
              number: 1,
            },
          ],
          isCustomField: false,
          accessor: "education",
          identifier: "education",
          originalIdentifier: "education",
          position: 7,
        },
        address: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.5c0f5c0cd7498fa3'),
          isVisible: true,
          children: {
            Line1: {
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.ed103e0317413dc5'),
              isVisible: true,
              isSpellCheck: false,
              children: {},
              dataType: DataType.STRING,
              defaultValue:
                "{{((sourceData, formData, fieldState) => (sourceData.address.Line1))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              fieldType: FieldType.TEXT_INPUT,
              iconAlign: "left",
              sourceData: $t('schemaTestData.cbeb6f28d88feaa9'),
              isCustomField: false,
              accessor: $t('schemaTestData.12280f5caa2d4d35'),
              identifier: $t('schemaTestData.12280f5caa2d4d35'),
              originalIdentifier: $t('schemaTestData.12280f5caa2d4d35'),
              position: 0,
              accentColor:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              borderRadius:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              boxShadow: "none",
            },
            city: {
              isSpellCheck: false,
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.29e7f29dffbe20ef'),
              isVisible: true,
              children: {},
              dataType: DataType.STRING,
              defaultValue:
                "{{((sourceData, formData, fieldState) => (sourceData.address.city))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              fieldType: FieldType.TEXT_INPUT,
              iconAlign: "left",
              sourceData: "1",
              isCustomField: false,
              accessor: "city",
              identifier: "city",
              originalIdentifier: "city",
              position: 1,
              accentColor:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              borderRadius:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              boxShadow: "none",
            },
          },
          dataType: DataType.OBJECT,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.address))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.OBJECT,
          sourceData: { Line1: $t('schemaTestData.cbeb6f28d88feaa9'), city: "1" },
          isCustomField: false,
          accessor: "address",
          identifier: "address",
          originalIdentifier: "address",
          position: 8,
        },
      },
      dataType: DataType.OBJECT,
      defaultValue:
        "{{((sourceData, formData, fieldState) => (sourceData))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
      fieldType: FieldType.OBJECT,
      sourceData: {
        name: $t('schemaTestData.546316e01bed24e3'),
        age: 20,
        dob: "10/12/2021",
        boolean: true,
        hobbies: ["travelling", "skating", "off-roading"],
        "%%": "%",
        education: [
          {
            college: $t('schemaTestData.cbeb6f28d88feaa9'),
            number: 1,
            graduationDate: "10/12/2021",
            boolean: true,
          },
        ],
        address: {
          Line1: $t('schemaTestData.cbeb6f28d88feaa9'),
          city: "1",
        },
        हिन्दि: "हिन्दि",
      },
      isCustomField: false,
      accessor: ROOT_SCHEMA_KEY,
      identifier: ROOT_SCHEMA_KEY,
      originalIdentifier: ROOT_SCHEMA_KEY,
      position: -1,
    },
  },
};

const withRemovedKeyFromInitialDataset = {
  dataSource: {
    name: $t('schemaTestData.546316e01bed24e3'),
    age: 20,
    dob: "10/12/2021",
    hobbies: ["travelling", "skating", "off-roading"],
    हिन्दि: "हिन्दि",
    education: [
      {
        college: $t('schemaTestData.cbeb6f28d88feaa9'),
        number: 1,
        graduationDate: "10/12/2021",
        boolean: true,
      },
    ],
    address: {
      Line1: $t('schemaTestData.cbeb6f28d88feaa9'),
      city: "1",
    },
  },

  schemaOutput: {
    __root_schema__: {
      isDisabled: false,
      isRequired: false,
      labelTextSize: "0.875rem",
      label: "",
      isVisible: true,
      children: {
        name: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.e6842984605930e9'),
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.name))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.TEXT_INPUT,
          iconAlign: "left",
          sourceData: $t('schemaTestData.546316e01bed24e3'),
          isCustomField: false,
          accessor: "name",
          identifier: "name",
          originalIdentifier: "name",
          position: 0,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        age: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.d17cce405d14d3db'),
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.NUMBER,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.age))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.NUMBER_INPUT,
          iconAlign: "left",
          sourceData: 20,
          isCustomField: false,
          accessor: "age",
          identifier: "age",
          originalIdentifier: "age",
          position: 1,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        dob: {
          closeOnSelection: false,
          dateFormat: "MM/DD/YYYY",
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.0aaed11e816c0059'),
          maxDate: "2121-12-31T18:29:00.000Z",
          minDate: "1920-12-31T18:30:00.000Z",
          shortcuts: false,
          isVisible: true,
          convertToISO: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            '{{((sourceData, formData, fieldState) => (moment(sourceData.dob, "MM/DD/YYYY").format("YYYY-MM-DDTHH:mm:ss.sssZ")))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}',
          fieldType: FieldType.DATEPICKER,
          timePrecision: "minute",
          sourceData: "10/12/2021",
          isCustomField: false,
          accessor: "dob",
          identifier: "dob",
          originalIdentifier: "dob",
          position: 2,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        hobbies: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.c6daaeb60a5a6839'),
          isVisible: true,
          serverSideFiltering: false,
          options: [
            { label: $t('schemaTestData.99051cd50140c8ee'), value: "BLUE" },
            { label: $t('schemaTestData.6e385a18e993129a'), value: "GREEN" },
            { label: $t('schemaTestData.98870409aa4c6131'), value: "RED" },
          ],
          children: {},
          dataType: DataType.ARRAY,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.hobbies))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.MULTISELECT,
          isFilterable: false,
          sourceData: ["travelling", "skating", "off-roading"],
          isCustomField: false,
          accessor: "hobbies",
          identifier: "hobbies",
          originalIdentifier: "hobbies",
          position: 4,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        xn__j2bd4cyac6f: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: "हिन्दि",
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            '{{((sourceData, formData, fieldState) => (sourceData["हिन्दि"]))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}',
          fieldType: FieldType.TEXT_INPUT,
          iconAlign: "left",
          sourceData: "हिन्दि",
          isCustomField: false,
          accessor: "हिन्दि",
          identifier: "xn__j2bd4cyac6f",
          originalIdentifier: "हिन्दि",
          position: 6,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        education: {
          backgroundColor: "#FAFAFA",
          isCollapsible: true,
          isDisabled: false,
          isRequired: false,
          isVisible: true,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.10a1cd2565283d7c'),
          children: {
            __array_item__: {
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.80fb12de536f6fd8'),
              isVisible: true,
              children: {
                college: {
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.76b513503aa00c46'),
                  isVisible: true,
                  isSpellCheck: false,
                  children: {},
                  dataType: DataType.STRING,
                  defaultValue: undefined,
                  fieldType: FieldType.TEXT_INPUT,
                  iconAlign: "left",
                  sourceData: $t('schemaTestData.cbeb6f28d88feaa9'),
                  isCustomField: false,
                  accessor: "college",
                  identifier: "college",
                  originalIdentifier: "college",
                  position: 0,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                number: {
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.66abdebf9a08121c'),
                  isVisible: true,
                  isSpellCheck: false,
                  children: {},
                  dataType: DataType.NUMBER,
                  defaultValue: undefined,
                  fieldType: FieldType.NUMBER_INPUT,
                  iconAlign: "left",
                  sourceData: 1,
                  isCustomField: false,
                  accessor: "number",
                  identifier: "number",
                  originalIdentifier: "number",
                  position: 1,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                graduationDate: {
                  closeOnSelection: false,
                  dateFormat: "MM/DD/YYYY",
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.369a4178adbfbc0d'),
                  maxDate: "2121-12-31T18:29:00.000Z",
                  minDate: "1920-12-31T18:30:00.000Z",
                  shortcuts: false,
                  isVisible: true,
                  convertToISO: false,
                  children: {},
                  dataType: DataType.STRING,
                  defaultValue: undefined,
                  fieldType: FieldType.DATEPICKER,
                  timePrecision: "minute",
                  sourceData: "10/12/2021",
                  isCustomField: false,
                  accessor: "graduationDate",
                  identifier: "graduationDate",
                  originalIdentifier: "graduationDate",
                  position: 2,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                boolean: {
                  alignWidget: "LEFT",
                  isDisabled: false,
                  isRequired: false,
                  isVisible: true,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.ae6da85839ef34ba'),
                  children: {},
                  dataType: DataType.BOOLEAN,
                  defaultValue: undefined,
                  fieldType: FieldType.SWITCH,
                  sourceData: true,
                  isCustomField: false,
                  accessor: "boolean",
                  identifier: "boolean",
                  originalIdentifier: "boolean",
                  position: 3,
                  backgroundColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
              },
              dataType: DataType.OBJECT,
              defaultValue: undefined,
              fieldType: FieldType.OBJECT,
              sourceData: {
                college: $t('schemaTestData.cbeb6f28d88feaa9'),
                number: 1,
                graduationDate: "10/12/2021",
                boolean: true,
              },
              isCustomField: false,
              accessor: ARRAY_ITEM_KEY,
              identifier: ARRAY_ITEM_KEY,
              originalIdentifier: ARRAY_ITEM_KEY,
              position: -1,
            },
          },
          dataType: DataType.ARRAY,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.education))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.ARRAY,
          sourceData: [
            {
              boolean: true,
              college: $t('schemaTestData.cbeb6f28d88feaa9'),
              graduationDate: "10/12/2021",
              number: 1,
            },
          ],
          isCustomField: false,
          accessor: "education",
          identifier: "education",
          originalIdentifier: "education",
          position: 7,
        },
        address: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.5c0f5c0cd7498fa3'),
          isVisible: true,
          children: {
            Line1: {
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.ed103e0317413dc5'),
              isVisible: true,
              isSpellCheck: false,
              children: {},
              dataType: DataType.STRING,
              defaultValue:
                "{{((sourceData, formData, fieldState) => (sourceData.address.Line1))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              fieldType: FieldType.TEXT_INPUT,
              iconAlign: "left",
              sourceData: $t('schemaTestData.cbeb6f28d88feaa9'),
              isCustomField: false,
              accessor: $t('schemaTestData.12280f5caa2d4d35'),
              identifier: $t('schemaTestData.12280f5caa2d4d35'),
              originalIdentifier: $t('schemaTestData.12280f5caa2d4d35'),
              position: 0,
              accentColor:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              borderRadius:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              boxShadow: "none",
            },
            city: {
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.29e7f29dffbe20ef'),
              isSpellCheck: false,
              isVisible: true,
              children: {},
              dataType: DataType.STRING,
              defaultValue:
                "{{((sourceData, formData, fieldState) => (sourceData.address.city))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              fieldType: FieldType.TEXT_INPUT,
              iconAlign: "left",
              sourceData: "1",
              isCustomField: false,
              accessor: "city",
              identifier: "city",
              originalIdentifier: "city",
              position: 1,
              accentColor:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              borderRadius:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              boxShadow: "none",
            },
          },
          dataType: DataType.OBJECT,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.address))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.OBJECT,
          sourceData: { Line1: $t('schemaTestData.cbeb6f28d88feaa9'), city: "1" },
          isCustomField: false,
          accessor: "address",
          identifier: "address",
          originalIdentifier: "address",
          position: 8,
        },
      },
      dataType: DataType.OBJECT,
      defaultValue:
        "{{((sourceData, formData, fieldState) => (sourceData))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
      fieldType: FieldType.OBJECT,
      sourceData: {
        name: $t('schemaTestData.546316e01bed24e3'),
        age: 20,
        dob: "10/12/2021",
        hobbies: ["travelling", "skating", "off-roading"],
        हिन्दि: "हिन्दि",
        education: [
          {
            college: $t('schemaTestData.cbeb6f28d88feaa9'),
            number: 1,
            graduationDate: "10/12/2021",
            boolean: true,
          },
        ],
        address: {
          Line1: $t('schemaTestData.cbeb6f28d88feaa9'),
          city: "1",
        },
      },
      isCustomField: false,
      accessor: ROOT_SCHEMA_KEY,
      identifier: ROOT_SCHEMA_KEY,
      originalIdentifier: ROOT_SCHEMA_KEY,
      position: -1,
    },
  },
};

const withRemovedAddedKeyToInitialDataset = {
  dataSource: {
    name: $t('schemaTestData.546316e01bed24e3'),
    age: 20,
    dob: "10/12/2021",
    gender: "male",
    hobbies: ["travelling", "skating", "off-roading"],
    हिन्दि: "हिन्दि",
    education: [
      {
        college: $t('schemaTestData.cbeb6f28d88feaa9'),
        number: 1,
        graduationDate: "10/12/2021",
        boolean: true,
      },
    ],
    address: {
      Line1: $t('schemaTestData.cbeb6f28d88feaa9'),
      city: "1",
    },
  },

  schemaOutput: {
    __root_schema__: {
      isDisabled: false,
      isRequired: false,
      labelTextSize: "0.875rem",
      label: "",
      isVisible: true,
      children: {
        name: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.e6842984605930e9'),
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.name))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.TEXT_INPUT,
          iconAlign: "left",
          sourceData: $t('schemaTestData.546316e01bed24e3'),
          isCustomField: false,
          accessor: "name",
          identifier: "name",
          originalIdentifier: "name",
          position: 0,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        age: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.d17cce405d14d3db'),
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.NUMBER,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.age))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.NUMBER_INPUT,
          iconAlign: "left",
          sourceData: 20,
          isCustomField: false,
          accessor: "age",
          identifier: "age",
          originalIdentifier: "age",
          position: 1,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        dob: {
          closeOnSelection: false,
          dateFormat: "MM/DD/YYYY",
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.0aaed11e816c0059'),
          maxDate: "2121-12-31T18:29:00.000Z",
          minDate: "1920-12-31T18:30:00.000Z",
          shortcuts: false,
          isVisible: true,
          children: {},
          dataType: DataType.STRING,
          convertToISO: false,
          defaultValue:
            '{{((sourceData, formData, fieldState) => (moment(sourceData.dob, "MM/DD/YYYY").format("YYYY-MM-DDTHH:mm:ss.sssZ")))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}',
          fieldType: FieldType.DATEPICKER,
          timePrecision: "minute",
          sourceData: "10/12/2021",
          isCustomField: false,
          accessor: "dob",
          identifier: "dob",
          originalIdentifier: "dob",
          position: 2,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        hobbies: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.c6daaeb60a5a6839'),
          isVisible: true,
          serverSideFiltering: false,
          options: [
            { label: $t('schemaTestData.99051cd50140c8ee'), value: "BLUE" },
            { label: $t('schemaTestData.6e385a18e993129a'), value: "GREEN" },
            { label: $t('schemaTestData.98870409aa4c6131'), value: "RED" },
          ],
          children: {},
          dataType: DataType.ARRAY,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.hobbies))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.MULTISELECT,
          isFilterable: false,
          sourceData: ["travelling", "skating", "off-roading"],
          isCustomField: false,
          accessor: "hobbies",
          identifier: "hobbies",
          originalIdentifier: "hobbies",
          position: 3,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        xn__j2bd4cyac6f: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: "हिन्दि",
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            '{{((sourceData, formData, fieldState) => (sourceData["हिन्दि"]))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}',
          fieldType: FieldType.TEXT_INPUT,
          iconAlign: "left",
          sourceData: "हिन्दि",
          isCustomField: false,
          accessor: "हिन्दि",
          identifier: "xn__j2bd4cyac6f",
          originalIdentifier: "हिन्दि",
          position: 4,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
        education: {
          backgroundColor: "#FAFAFA",
          isCollapsible: true,
          isDisabled: false,
          isRequired: false,
          isVisible: true,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.10a1cd2565283d7c'),
          children: {
            __array_item__: {
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.80fb12de536f6fd8'),
              isVisible: true,
              children: {
                college: {
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.76b513503aa00c46'),
                  isVisible: true,
                  isSpellCheck: false,
                  children: {},
                  dataType: DataType.STRING,
                  defaultValue: undefined,
                  fieldType: FieldType.TEXT_INPUT,
                  iconAlign: "left",
                  sourceData: $t('schemaTestData.cbeb6f28d88feaa9'),
                  isCustomField: false,
                  accessor: "college",
                  identifier: "college",
                  originalIdentifier: "college",
                  position: 0,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                number: {
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.66abdebf9a08121c'),
                  isVisible: true,
                  isSpellCheck: false,
                  children: {},
                  dataType: DataType.NUMBER,
                  defaultValue: undefined,
                  fieldType: FieldType.NUMBER_INPUT,
                  iconAlign: "left",
                  sourceData: 1,
                  isCustomField: false,
                  accessor: "number",
                  identifier: "number",
                  originalIdentifier: "number",
                  position: 1,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                graduationDate: {
                  closeOnSelection: false,
                  dateFormat: "MM/DD/YYYY",
                  isDisabled: false,
                  isRequired: false,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.369a4178adbfbc0d'),
                  maxDate: "2121-12-31T18:29:00.000Z",
                  minDate: "1920-12-31T18:30:00.000Z",
                  shortcuts: false,
                  isVisible: true,
                  children: {},
                  dataType: DataType.STRING,
                  defaultValue: undefined,
                  fieldType: FieldType.DATEPICKER,
                  timePrecision: "minute",
                  sourceData: "10/12/2021",
                  convertToISO: false,
                  isCustomField: false,
                  accessor: "graduationDate",
                  identifier: "graduationDate",
                  originalIdentifier: "graduationDate",
                  position: 2,
                  accentColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  borderRadius:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
                boolean: {
                  alignWidget: "LEFT",
                  isDisabled: false,
                  isRequired: false,
                  isVisible: true,
                  labelTextSize: "0.875rem",
                  label: $t('schemaTestData.ae6da85839ef34ba'),
                  children: {},
                  dataType: DataType.BOOLEAN,
                  defaultValue: undefined,
                  fieldType: FieldType.SWITCH,
                  sourceData: true,
                  isCustomField: false,
                  accessor: "boolean",
                  identifier: "boolean",
                  originalIdentifier: "boolean",
                  position: 3,
                  backgroundColor:
                    "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
                  boxShadow: "none",
                },
              },
              dataType: DataType.OBJECT,
              defaultValue: undefined,
              fieldType: FieldType.OBJECT,
              sourceData: {
                college: $t('schemaTestData.cbeb6f28d88feaa9'),
                number: 1,
                graduationDate: "10/12/2021",
                boolean: true,
              },
              isCustomField: false,
              accessor: ARRAY_ITEM_KEY,
              identifier: ARRAY_ITEM_KEY,
              originalIdentifier: ARRAY_ITEM_KEY,
              position: -1,
            },
          },
          dataType: DataType.ARRAY,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.education))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.ARRAY,
          sourceData: [
            {
              boolean: true,
              college: $t('schemaTestData.cbeb6f28d88feaa9'),
              graduationDate: "10/12/2021",
              number: 1,
            },
          ],
          isCustomField: false,
          accessor: "education",
          identifier: "education",
          originalIdentifier: "education",
          position: 5,
        },
        address: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.5c0f5c0cd7498fa3'),
          isVisible: true,
          children: {
            Line1: {
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.ed103e0317413dc5'),
              isVisible: true,
              isSpellCheck: false,
              children: {},
              dataType: DataType.STRING,
              defaultValue:
                "{{((sourceData, formData, fieldState) => (sourceData.address.Line1))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              fieldType: FieldType.TEXT_INPUT,
              iconAlign: "left",
              sourceData: $t('schemaTestData.cbeb6f28d88feaa9'),
              isCustomField: false,
              accessor: $t('schemaTestData.12280f5caa2d4d35'),
              identifier: $t('schemaTestData.12280f5caa2d4d35'),
              originalIdentifier: $t('schemaTestData.12280f5caa2d4d35'),
              position: 0,
              accentColor:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              borderRadius:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              boxShadow: "none",
            },
            city: {
              isSpellCheck: false,
              isDisabled: false,
              isRequired: false,
              labelTextSize: "0.875rem",
              label: $t('schemaTestData.29e7f29dffbe20ef'),
              isVisible: true,
              children: {},
              dataType: DataType.STRING,
              defaultValue:
                "{{((sourceData, formData, fieldState) => (sourceData.address.city))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              fieldType: FieldType.TEXT_INPUT,
              iconAlign: "left",
              sourceData: "1",
              isCustomField: false,
              accessor: "city",
              identifier: "city",
              originalIdentifier: "city",
              position: 1,
              accentColor:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              borderRadius:
                "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
              boxShadow: "none",
            },
          },
          dataType: DataType.OBJECT,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.address))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.OBJECT,
          sourceData: { Line1: $t('schemaTestData.cbeb6f28d88feaa9'), city: "1" },
          isCustomField: false,
          accessor: "address",
          identifier: "address",
          originalIdentifier: "address",
          position: 6,
        },
        gender: {
          isDisabled: false,
          isRequired: false,
          labelTextSize: "0.875rem",
          label: $t('schemaTestData.b7f68e1ffcd754eb'),
          isVisible: true,
          isSpellCheck: false,
          children: {},
          dataType: DataType.STRING,
          defaultValue:
            "{{((sourceData, formData, fieldState) => (sourceData.gender))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          fieldType: FieldType.TEXT_INPUT,
          iconAlign: "left",
          sourceData: "male",
          isCustomField: false,
          accessor: "gender",
          identifier: "gender",
          originalIdentifier: "gender",
          position: 7,
          accentColor:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.colors.primaryColor)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          borderRadius:
            "{{((sourceData, formData, fieldState) => ((appsmith.theme.borderRadius.appBorderRadius)))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
          boxShadow: "none",
        },
      },
      dataType: DataType.OBJECT,
      defaultValue:
        "{{((sourceData, formData, fieldState) => (sourceData))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}",
      fieldType: FieldType.OBJECT,
      sourceData: {
        name: $t('schemaTestData.546316e01bed24e3'),
        age: 20,
        dob: "10/12/2021",
        gender: "male",
        hobbies: ["travelling", "skating", "off-roading"],
        हिन्दि: "हिन्दि",
        education: [
          {
            college: $t('schemaTestData.cbeb6f28d88feaa9'),
            number: 1,
            graduationDate: "10/12/2021",
            boolean: true,
          },
        ],
        address: {
          Line1: $t('schemaTestData.cbeb6f28d88feaa9'),
          city: "1",
        },
      },
      isCustomField: false,
      accessor: ROOT_SCHEMA_KEY,
      identifier: ROOT_SCHEMA_KEY,
      originalIdentifier: ROOT_SCHEMA_KEY,
      position: -1,
    },
  },
};

const fieldThemeStylesheets = {
  CHECKBOX: {
    backgroundColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  CURRENCY_INPUT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  DATEPICKER: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  EMAIL_INPUT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  MULTISELECT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  MULTILINE_TEXT_INPUT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  NUMBER_INPUT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  PASSWORD_INPUT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  PHONE_NUMBER_INPUT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  RADIO_GROUP: {
    backgroundColor: "{{appsmith.theme.colors.primaryColor}}",
    boxShadow: "none",
  },
  SELECT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
  SWITCH: {
    backgroundColor: "{{appsmith.theme.colors.primaryColor}}",
    boxShadow: "none",
  },
  TEXT_INPUT: {
    accentColor: "{{appsmith.theme.colors.primaryColor}}",
    borderRadius: "{{appsmith.theme.borderRadius.appBorderRadius}}",
    boxShadow: "none",
  },
} as unknown as FieldThemeStylesheet;

export default {
  initialDataset,
  withRemovedKeyFromInitialDataset,
  withRemovedAddedKeyToInitialDataset,
  fieldThemeStylesheets,
};
