import {$t} from "locale/index";
import { ResponsiveBehavior } from "layoutSystems/common/utils/constants";
import type { WidgetDefaultProps } from "WidgetProvider/constants";

export const defaultsConfig = {
  widgetName: "ToolbarButtons",
  orientation: "horizontal",
  variant: "ghost",
  color: "accent",
  isDisabled: false,
  isVisible: true,
  version: 1,
  animateLoading: true,
  responsiveBehavior: ResponsiveBehavior.Fill,
  buttonsList: {
    button1: {
      label: $t('defaultsConfig.63727ad3e1da4e1b'),
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "button1",
      index: 0,
      icon: "plus",
      iconPosition: "start",
    },
    button2: {
      label: $t('defaultsConfig.58385649c5534ec8'),
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "button2",
      index: 1,
      icon: "pencil",
      iconPosition: "start",
    },
    button3: {
      label: $t('defaultsConfig.1d135453a399369a'),
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "button3",
      index: 2,
      icon: "copy",
      iconPosition: "start",
    },
    separator: {
      isVisible: true,
      isDisabled: false,
      isSeparator: true,
      widgetId: "",
      id: "separator",
      index: 2,
      label: $t('defaultsConfig.67d5c60df6f478a8'),
      itemType: "SEPARATOR",
    },
    button4: {
      label: $t('defaultsConfig.e348fe900b4938c6'),
      isVisible: true,
      isDisabled: false,
      widgetId: "",
      id: "button4",
      index: 2,
      icon: "trash",
      iconPosition: "start",
    },
  },
} as unknown as WidgetDefaultProps;
